### ISSUE TITLE
Bqf doesn't work if lazy loaded

### ISSUE THREAD

**Issue by williamgoulois** [abzcoding/lvim#116]
Hi abz !

Just updated my config today to use Lazy and saw that the plugin nvim-bqf is not loaded
I removed `lazy = true` to make it work but dunno if we could find a better solution 🙂 
<img width="1424" alt="Screenshot 2023-01-14 at 23 51 06" src="https://user-images.githubusercontent.com/37271970/212500543-b9126d7c-d993-4fee-9d1c-edcc9f547171.png">

**Comment by williamgoulois** [comment]
Seeing this list spectre is not loaded too 😢

**Comment by abzcoding** [comment]
spectre should only load when you call it ( for example by pressing `<Leader>Rp`

**Comment by williamgoulois** [comment]
<Leader>R goes into "replace" mode after cursor and i do not have the `:Spectre` command
The command `Spectre` appears if i remove `lazy = true` but it is still not working with `<Leader>Rp`

**Comment by abzcoding** [comment]
> R goes into "replace" mode after cursor and i do not have the `:Spectre` command
> The command `Spectre` appears if i remove `lazy = true` but it is still not working with `<Leader>Rp`

I'm using it right now 😅 

https://github.com/abzcoding/lvim/blob/5cde48dde6c297cb33883891da1dead70f73d4d7/lua/user/keybindings.lua#L385

**Comment by williamgoulois** [comment]
> I'm using it right now 😅

Correction : It works ! 🎉 

i had an error in my config.lua. There was a line requiring `notify` to change config but I disabled noice that required it (because of the bug in neovim)

**Comment by abzcoding** [comment]
the bqf problem should be fixed in the latest commit

**Comment by williamgoulois** [comment]
But I still have the issue with nvim-bqf, maybe we can add event `VeryLazy` ?

**Comment by williamgoulois** [comment]
> the bqf problem should be fixed in the latest commit

Ok lemme try that 😁

**Comment by abzcoding** [comment]
`VeryLazy` seems to be a viable option as well

**Comment by williamgoulois** [comment]
Ok woks perfectly thanks for the quick reply as always ! 🙇 
I am closing this issue as resolved 🎉
